export const RESIGNED_URL_EXPIRES_IN = 300;

// Dependency Injection Symbols

// REPOSITORY
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const PROFILE_REPOSITORY = Symbol('PROFILE_REPOSITORY');
export const TOKEN_REPOSITORY = Symbol('TOKEN_REPOSITORY');
export const INVITE_CODE_REPOSITORY = Symbol('INVITE_CODE_REPOSITORY');
export const FRIENDSHIP_REPOSITORY = Symbol('FRIENDSHIP_REPOSITORY');
export const FRIENDSHIP_ACTIVITY_REPOSITORY = Symbol('FRIENDSHIP_ACTIVITY_REPOSITORY');
export const FRIEND_REQUEST_REPOSITORY = Symbol('FRIEND_REQUEST_REPOSITORY');

// QUERY
export const FRIENDSHIP_QUERY_REPOSITORY = Symbol('FRIENDSHIP_QUERY_REPOSITORY');

// Mongo
export const FEED_REPOSITORY = Symbol('FEED_REPOSITORY');
