// Dependency Injection Symbols

// REPOSITORY
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const PROFILE_REPOSITORY = Symbol('PROFILE_REPOSITORY');
export const TOKEN_REPOSITORY = Symbol('TOKEN_REPOSITORY');
export const INVITE_CODE_REPOSITORY = Symbol('INVITE_CODE_REPOSITORY');
export const FRIENDSHIP_REPOSITORY = Symbol('FRIENDSHIP_REPOSITORY');
export const FRIENDSHIP_ACTIVITY_REPOSITORY = Symbol('FRIENDSHIP_ACTIVITY_REPOSITORY');
export const FRIEND_REQUEST_REPOSITORY = Symbol('FRIEND_REQUEST_REPOSITORY');
export const BOOKMARK_REPOSITORY = Symbol('BOOKMARK_REPOSITORY');
export const RESTAURANT_REPOSITORY = Symbol('RESTAURANT_REPOSITORY');
export const PIN_REPOSITORY = Symbol('PIN_REPOSITORY');

// QUERY !추후 REPOSITORY Name Space 제거 예정
export const FRIENDSHIP_QUERY_REPOSITORY = Symbol('FRIENDSHIP_QUERY_REPOSITORY');
export const USER_QUERY_REPOSITORY = Symbol('USER_QUERY_REPOSITORY');
export const BOOKMARK_QUERY_REPOSITORY = Symbol('BOOKMARK_QUERY_REPOSITORY');
export const PIN_QUERY_REPOSITORY = Symbol('PIN_QUERY_REPOSITORY');

// Mongo
export const FEED_REPOSITORY = Symbol('FEED_REPOSITORY');

// SERVICE
export const FILE_UPLOAD_SERVICE = Symbol('FILE_UPLOAD_SERVICE');
